addSbtPlugin("ch.epfl.scala"           % "sbt-missinglink"     % "0.3.2" )
addSbtPlugin("com.eed3si9n"            % "sbt-buildinfo"       % "0.10.0")
addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat"       % "1.1.0" )
addSbtPlugin("com.github.sbt"          % "sbt-native-packager" % "1.9.2" )
addSbtPlugin("io.spray"                % "sbt-revolver"        % "0.9.1" )
